[[top]]

https://github.com/Aarav-USA/LP3THW-Progress/graphs/contributors[image:https://img.shields.io/github/contributors/Aarav-USA/LP3THW-Progress.svg?style=for-the-badge[Contributors]]
https://github.com/Aarav-USA/LP3THW-Progress/network/members[image:https://img.shields.io/github/forks/Aarav-USA/LP3THW-Progress.svg?style=for-the-badge[Forks]]
https://github.com/Aarav-USA/LP3THW-Progress/stargazers[image:https://img.shields.io/github/stars/Aarav-USA/LP3THW-Progress.svg?style=for-the-badge[Stargazers]]
https://github.com/Aarav-USA/LP3THW-Progress/issues[image:https://img.shields.io/github/issues/Aarav-USA/LP3THW-Progress.svg?style=for-the-badge[Issues]]
https://github.com/Aarav-USA/LP3THW-Progress/blob/main/LICENSE[image:https://img.shields.io/github/license/Aarav-USA/LP3THW-Progress.svg?style=for-the-badge[MIT]]

= Learn Python 3 The Hard Way Progress

An upload of Learn Python 3 The Hard Way Progress.
LP3THW is a book of exercises that help learn Python through practice.

:toc:

== About The Project

`LP3THW-Progress` publishes the progress of learning Python3.
Learning code “the hard way” is learning with repetition; reinforcing concepts that are hard to understand.


=== Built With
// Refs:
:url-python: https://www.python.org
:url-asciidoctor: https://asciidoctor.org
:url-dependabot: https://github.com/dependabot

- {url-python}[Python 3.9]
- {url-asciidoctor}[Asciidoctor]
- {url-dependabot}[Dependabot]


== Getting Started

These are the instructions of how to set up the project locally.
To get a local copy up and running follow these simple steps.

=== Prerequisites
// Refs
:url-python: https://www.python.org/downloads
:url-docs: https://docs.python.org/3

Python must be installed to run `.py` files.
Go to the {url-python}[Python website] click download, and run the installer.
Refer to the {url-docs}[documentation] for troubleshooting.


=== Installation

. Clone the repo via HTTPS or add `.git` for SSH
+
[source,sh]
----
git clone https://github.com/Aarav-USA/LP3THW-Progress
----
. Change directory
+
[source,sh]
----
cd LP3THW-Progress
----
. Run Python3 Test File
+
[source,sh]
----
python3 test.py
----
. Run other files
+
[source,sh]
----
python3 ex/(exercise number).py
----


== Contributing

Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
Any contributions you make are *greatly appreciated*.

If you have a suggestion that would make this better, please fork the repo and create a pull request.
You can also simply open an issue with the tag `enhancement`.
Don’t forget to give the project a star!
Thanks again!

1. Fork the Project
2. Create your Feature Branch (`git checkout -b feature/AmazingFeature`)
3. Commit your Changes (`git commit -m 'Add some AmazingFeature'`)
4. Push to the Branch (`git push origin feature/AmazingFeature`)
5. Open a Pull Request


== License

Distributed under the MIT license.
See `LICENSE` for more information.


== Contact
// Refs:
:url-profile: https://github.com/Aarav-USA
:url-project: https://github.com/Aarav-USA/LP3THW-Progress

Aarav - {url-profile}}[GitHub Profile] - aarav-usa@pm.me

Project Link:
{url-project}[LP3THW-Progress]


== Acknowledgments
// Refs:
:url-template: https://github.com/othneildrew/Best-README-Template/blob/master/LICENSE.txt
:url-book: https://github.com/immu0001/Learn-Python-3-The-Hard-Way
:url-shields: https://shields.io/

- {url-template}[Best README Template License]
- {url-book}[Learn Python 3 The Hard Way]
- {url-shields}[README Header Shield]
