print("What is your name?", end = ' ')
name = input()
print("Where are you from?", end = ' ')
nationality = input()
print("How old are you?", end = ' ')
age = input()
print("How are you doing?", end = ' ')
mood = input()
print("What do you like to do?", end = ' ')
hobbies = input()

print(f"So your name is {name}, you're from {nationality}, you are {age} years old, you are feeling {mood}, and you like {hobbies}.")
